# Deep Learning

In [4]:
import torch
import torchvision  #  dataset, model va hakazo transformation

In [6]:
from torchvision.datasets import MNIST

In [8]:
from torchvision import transforms as T
# mean = [0.485, 0.456, 0.406]
# std = [0.229, 0.224, 0.225]
mean = [0.5]
std = [0.5]
tfs = T.Compose([T.ToTensor(), T.Normalize(mean=mean, std=std)])
train_dataset = MNIST(root="datasetlar", train = True, download=True, transform=tfs)
test_dataset = MNIST(root="datasetlar", train=False, download=True, transform=tfs)

In [11]:
data = train_dataset[2]
rasm, javob = data

In [12]:
rasm.shape

torch.Size([1, 28, 28])

In [13]:
torch.unique(rasm) # unique bu berilgan tensordagi takrorlanmaydigan (unique) qiymatlarni topib, ularни tartiblangan holda qaytaradi. 
#Ya'ni tensordagi barcha turli xil qiymatlarni bir marta chiqaradi, takrorlanganlarни olib tashlaydi.
# yani rasm = torch.tensor([1, 2, 2, 3, 3, 3, 5])
#print(torch.unique(rasm)) tensor()[1,2,3,5,] chiqadi.

tensor([-1.0000, -0.9843, -0.9608, -0.8902, -0.8745, -0.8196, -0.7882, -0.7804,
        -0.7725, -0.6941, -0.6863, -0.6392, -0.6314, -0.6157, -0.5608, -0.5529,
        -0.5137, -0.4745, -0.3647, -0.3333, -0.3255, -0.2863, -0.2627, -0.2471,
        -0.2314, -0.2000, -0.0902, -0.0667, -0.0588, -0.0196, -0.0118,  0.0745,
         0.1216,  0.1294,  0.1765,  0.2000,  0.2471,  0.2706,  0.2784,  0.3255,
         0.3882,  0.3961,  0.4039,  0.4118,  0.4353,  0.5529,  0.6235,  0.6471,
         0.6941,  0.7255,  0.7412,  0.8118,  0.8196,  0.8275,  0.8353,  0.8588,
         0.8824,  0.8902,  0.9059,  0.9216,  0.9451,  0.9608,  0.9765,  0.9843,
         0.9922,  1.0000])

In [14]:
rasm.size #PLT -> Tensor
type(rasm)

torch.Tensor

In [15]:
from torch.utils.data import random_split # random_split — bu PyTorch'ning torch.utils.data modulidagi funksiya bo'lib, bitta datasetni tasodifiy (random) ravishda ikki yoki undan ko'p qismlarga bo'lib beradi.
total_len = len(train_dataset) # — datasetdagi jami elementlar (rasmlar) sonini qaytaradi.
tr_len = int(total_len * 0.9) # Jami ma'lumotning **90%**ini train uchun ajratish hisoblanmoqda. #total_len * 0.9 = 60000 * 0.9 = 54000.0 (float son chiqadi).
vl_len = total_len - tr_len # umumiy uzunlikdan tr_len qiymatini olib tashlamoqda.
tr_len, vl_len

(54000, 6000)

In [16]:
tr_ds, vl_ds = random_split(train_dataset,[tr_len, vl_len])
len(tr_ds), len(vl_ds) #  train_dataset, valid_dataset - tr_ds, vl_ds qisqartma yozish.
type(tr_ds)
ts_ds = test_dataset

# DataLoader

In [17]:
from torch.utils.data import DataLoader
bs= 128 # batch_size - bs qisqartma yozish._
tr_dl = DataLoader(dataset = tr_ds, shuffle=True, batch_size = bs, num_workers = 0 ) # train_dataset qisqartmasi tr_ds
vl_dl = DataLoader(dataset = vl_ds, shuffle=False, batch_size = bs, num_workers = 0 ) # validation_dataset qisqartmasi vl_ds
ts_dl = DataLoader(dataset = ts_ds, shuffle=False, batch_size = bs, num_workers = 0 ) # test_dataset qisqartmasi ts_ds

In [20]:
mini_batch = next(iter(tr_dl)) # tr_dl dan birinchi mini_batch ni olish

In [21]:
rasmlar, javoblar = mini_batch

In [22]:
rasmlar.shape # batch_size, channel, height, width -> bs, im_chs. im_h, im_w

torch.Size([128, 1, 28, 28])

In [23]:
javoblar.shape

torch.Size([128])

In [24]:
rasm.shape

torch.Size([1, 28, 28])

# Custom Model



In [28]:
test_tensor_1 = torch.rand(2, 3)
test_tensor_2 = torch.rand(2, 3)
test_tensor_1 * test_tensor_2 # element wise multiplication qiymatlarini bir biriga ko'paytirish.

tensor([[2.9156e-04, 7.7323e-01, 2.2248e-01],
        [1.6127e-02, 6.1827e-01, 4.7206e-02]])

In [29]:
(test_tensor_1 @ test_tensor_2).shape # matrix multiplication

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [30]:
torch.multiply(test_tensor_1, test_tensor_2)

tensor([[2.9156e-04, 7.7323e-01, 2.2248e-01],
        [1.6127e-02, 6.1827e-01, 4.7206e-02]])

In [31]:
test_tensor_1 = torch.rand(12, 3)
test_tensor_2 = torch.rand(3, 4)
(test_tensor_1 @ test_tensor_2).shape 

torch.Size([12, 4])

In [32]:
# (a, b), (b, a); b == b --> (a, a)

In [33]:
inp = torch.rand(1,1,28,28) # (bs, im_channels, im_height, im_width)
inp.shape

torch.Size([1, 1, 28, 28])

In [34]:
28 * 28 * 1

784

In [35]:
test_inp = torch.rand(2,3,3,3,3,2,3,2)
test_inp.view(2,2,2, -1).shape 

torch.Size([2, 2, 2, 243])

In [36]:
test_inp = torch.rand(10, 1, 28, 28)
bs = test_inp.shape[0]
test_inp.view(bs, -1).shape # bs bu 10, -1 esa 1 va 28*28 ni ko'paytmasi

torch.Size([10, 784])

In [37]:
inp.shape
inp = inp.view(1, 784) # (bs, fts)
lin = Linear(in_features = 784, out_features = 1024) # (bs , fts)
lin(inp).shape # (bs, fts) -> (1, 1024)

torch.Size([1, 1024])

In [42]:
from torch.nn import *

# Moduledan inheritance qilganda 2 ta funciton o'zgartirilishi kerak:
# init
# forward - classni chaqirganda qanday amallar bajarishini ko'rsatadi.


import torch
from torch.nn import *

# Model yaratish uchun nn.Module dan inheritance qilamiz
class CustomModel(Module):
    def __init__(self, in_fs, out_fs, klasslar_soni):
        super().__init__()

        self.linear_1 = Linear(in_features=in_fs, out_features=out_fs)
        self.linear_2 = Linear(in_features=out_fs, out_features=out_fs * 4)
        self.linear_3 = Linear(in_features=out_fs * 4, out_features=klasslar_soni)

        self.relu = ReLU()

    def forward(self, x):
        bs = x.shape[0]

        # 4D tensor -> 2D tensor
        x = x.view(bs, -1)

        out = self.linear_1(x)
        out = self.relu(out)

        out = self.linear_2(out)
        out = self.relu(out)

        out = self.linear_3(out)

        return out


inp = torch.rand(1, 1, 28, 28)

model = CustomModel(
    in_fs=784,
    out_fs=200,
    klasslar_soni=10
)

result = model(inp)

print(result)
print(result.shape)


tensor([[-0.0407,  0.0790, -0.0850, -0.0975, -0.0488, -0.0048, -0.0746, -0.0295,
         -0.0146, -0.0007]], grad_fn=<AddmmBackward0>)
torch.Size([1, 10])
