In [28]:
import torch
import torchvision
from torch.nn import Module, Linear, ReLU, LeakyReLU, ELU, PReLU, GELU, SiLU, Softmax, Sigmoid

In [2]:
# activations — Activation Functions (faollashtirish funksiyalari) degani.
# activations = [ ReLU, LeakyReLU, ELU, PReLU, GELU, SiLU ]

# ReLu Hidden Layer

In [3]:
## 1 - model 2 hidden layer ReLU
class CustomModel_1(Module):
    def __init__(self,in_fs, out_fs, n_cls):
        super().__init__()
        self.hidden1 = Linear(in_features=in_fs, out_features=out_fs)
        self.activation1 = ReLU()

        self.hidden2 = Linear(in_features=out_fs, out_features=out_fs)
        self.activation2 = ReLU()
        self.classifier = Linear(in_features=out_fs, out_features=n_cls)

    def forward(self, input):
        bs = input.shape[0]
        input = input.view(bs, -1) # 2D ga o'zgartirish uchun.

        out = self.hidden1(input)
        out = self.activation1(out)    
        out = self.hidden2(out)
        out = self.activation2(out)
        out = self.classifier(out)
        return out
input = torch.rand(1, 1, 28, 28)
out_function = 200
model = CustomModel_1(in_fs = (input.shape[1] * input.shape[2] * input.shape[3]), out_fs = out_function, n_cls = 10)
model(input)

tensor([[ 0.0135, -0.0230,  0.1024,  0.0237,  0.0232,  0.0527,  0.0042, -0.0487,
          0.0415, -0.0868]], grad_fn=<AddmmBackward0>)

# LeakyReLU Hidden Layer

In [ ]:
## 2 - model 2 hidden layer LeakyReLU
class CustomModel_2(Module):
    def __init__(self,in_fs, out_fs, n_cls):
        super().__init__()
        self.hidden1 = Linear(in_features=in_fs, out_features=out_fs)
        self.activation1 = LeakyReLU()

        self.hidden2 = Linear(in_features=out_fs, out_features=out_fs)
        self.activation2 = LeakyReLU()
        self.classifier = Linear(in_features=out_fs, out_features=n_cls)

    def forward(self, input):
        bs = input.shape[0]
        input = input.view(bs, -1) # 2D ga o'zgartirish uchun.

        out = self.hidden1(input)
        out = self.activation1(out)    
        out = self.hidden2(out)
        out = self.activation2(out)
        out = self.classifier(out)
        return out
input = torch.rand(1, 1, 28, 28)
out_function = 200
model = CustomModel_2(in_fs = (input.shape[1] * input.shape[2] * input.shape[3]), out_fs = out_function, n_cls = 10)
model(input)

tensor([[-0.1268,  0.0531,  0.0244,  0.0712, -0.0320,  0.0609,  0.0805, -0.0167,
          0.0230, -0.1114]], grad_fn=<AddmmBackward0>)

# ELU Hidden Layer

In [ ]:
## 3 - model 2 hidden layer ELU
class CustomModel_3(Module):
    def __init__(self,in_fs, out_fs, n_cls):
        super().__init__()
        self.hidden1 = Linear(in_features=in_fs, out_features=out_fs)
        self.activation1 = ELU()

        self.hidden2 = Linear(in_features=out_fs, out_features=out_fs)
        self.activation2 = ELU()
        self.classifier = Linear(in_features=out_fs, out_features=n_cls)

    def forward(self, input):
        bs = input.shape[0]
        input = input.view(bs, -1) # 2D ga o'zgartirish uchun.

        out = self.hidden1(input)
        out = self.activation1(out)    
        out = self.hidden2(out)
        out = self.activation2(out)
        out = self.classifier(out)
        return out
input = torch.rand(1, 1, 28, 28)
out_function = 200
model = CustomModel_3(in_fs = (input.shape[1] * input.shape[2] * input.shape[3]), out_fs = out_function, n_cls = 10)
model(input)

tensor([[ 0.4076, -0.2647, -0.1631,  0.0054,  0.0153, -0.0308,  0.0562,  0.1313,
         -0.1876, -0.0540]], grad_fn=<AddmmBackward0>)

# PReLU Hidden Layer

In [ ]:
## 4 - model 2 hidden layer PReLU
class CustomModel_4(Module):
    def __init__(self,in_fs, out_fs, n_cls):
        super().__init__()
        self.hidden1 = Linear(in_features=in_fs, out_features=out_fs)
        self.activation1 = PReLU()

        self.hidden2 = Linear(in_features=out_fs, out_features=out_fs)
        self.activation2 = PReLU()
        self.classifier = Linear(in_features=out_fs, out_features=n_cls)

    def forward(self, input):
        bs = input.shape[0]
        input = input.view(bs, -1) # 2D ga o'zgartirish uchun.

        out = self.hidden1(input)
        out = self.activation1(out)    
        out = self.hidden2(out)
        out = self.activation2(out)
        out = self.classifier(out)
        return out
input = torch.rand(1, 1, 28, 28)
out_function = 200
model = CustomModel_4(in_fs = (input.shape[1] * input.shape[2] * input.shape[3]), out_fs = out_function, n_cls = 10)
model(input)

tensor([[ 0.0763,  0.0812,  0.0321,  0.0671,  0.0505,  0.0387,  0.0931, -0.0409,
          0.0144,  0.0122]], grad_fn=<AddmmBackward0>)

# GELU Hidden Layer 
(Exponential Linear Unit) — bu ReLU ga o'xshash, lekin u manfiy qiymatlar uchun eksponensial funktsiyani ishlatadi. Bu gradientning yo'qolishini kamaytiradi va neyron tarmoqni yaxshiroq o'qitishga yordam beradi.



In [10]:
## 5 - model 2 hidden layer GELU
class CustomModel_5(Module):
    def __init__(self,in_fs, out_fs, n_cls):
        super().__init__()
        self.hidden1 = Linear(in_features=in_fs, out_features=out_fs)
        self.activation1 = GELU()

        self.hidden2 = Linear(in_features=out_fs, out_features=out_fs)
        self.activation2 = GELU()
        self.classifier = Linear(in_features=out_fs, out_features=n_cls)

    def forward(self, input):
        bs = input.shape[0]
        input = input.view(bs, -1) # 2D ga o'zgartirish uchun.

        out = self.hidden1(input)
        out = self.activation1(out)    
        out = self.hidden2(out)
        out = self.activation2(out)
        out = self.classifier(out)
        return out
input = torch.rand(1, 1, 28, 28)
out_function = 200
model = CustomModel_5(in_fs = (input.shape[1] * input.shape[2] * input.shape[3]), out_fs = out_function, n_cls = 10)
model(input)

tensor([[-0.0638, -0.0549,  0.0292,  0.1008,  0.0021,  0.0977, -0.0373,  0.0107,
         -0.0933,  0.0680]], grad_fn=<AddmmBackward0>)

# SiLU 3 Hidden Layer

In [14]:
### (6 - Module) 2 hidden layer - SiLU
class CustomModel_6(Module):
    def __init__(self, in_fs, out_fs, n_cls):
        super().__init__()
        self.hidden1 = Linear(in_features=in_fs, out_features=out_fs)
        self.act1 = SiLU()

        self.hidden2 = Linear(in_features=out_fs, out_features=out_fs)
        self.act2 = SiLU()
        self.classifier = Linear(in_features=out_fs, out_features=n_cls)

    def forward(self, inp):
        bs = inp.shape[0]
        inp = inp.view(bs, -1)

        out = self.hidden1(inp)
        out = self.act1(out)
        out = self.hidden2(out)
        out = self.act2(out)
        out = self.classifier(out)
        return out

inp = torch.rand(1,1,28,28)
out_fs = 200
m = CustomModel_6(in_fs = (inp.shape[1] * inp.shape[2] * inp.shape[3]), out_fs = out_fs, n_cls = 10)
m(inp)

tensor([[-0.0331, -0.0970,  0.0511,  0.0857,  0.0173,  0.0316, -0.0343,  0.0019,
          0.0690, -0.0685]], grad_fn=<AddmmBackward0>)

4 - Hiiden Layer  barcha Hidden Layer kelish tartibi bir xil bulgani uchun 3-Hidden layerni qoldirdim.
(1-module)
#  ReLu

In [16]:
### (1 - module) 4 hidden layer - ReLu
class CustomModel_4H_1(Module):
    def __init__(self, in_fs, out_fs, n_cls):
        super().__init__()
        self.hidden1 = Linear(in_features=in_fs, out_features=out_fs)
        self.act1 = ReLU()

        self.hidden2 = Linear(in_features=out_fs, out_features=out_fs)
        self.act2 = ReLU()

        self.hidden3 = Linear(in_features=out_fs, out_features=out_fs)
        self.act3 = ReLU()

        self.hidden4 = Linear(in_features=out_fs, out_features=out_fs)
        self.act4 = ReLU()
        self.classifier = Linear(in_features=out_fs, out_features=n_cls)

    def forward(self, inp):
        bs = inp.shape[0]
        inp = inp.view(bs, -1)

        out = self.hidden1(inp)
        out = self.act1(out)
        out = self.hidden2(out)
        out = self.act2(out)
        out = self.hidden3(out)
        out = self.act3(out)
        out = self.hidden4(out)
        out = self.act4(out)
        out = self.classifier(out)
        return out

inp = torch.rand(1,1,28,28)
out_fs = 200
m = CustomModel_4H_1(in_fs = (inp.shape[1] * inp.shape[2] * inp.shape[3]), out_fs = out_fs, n_cls = 10)
m(inp)

tensor([[ 0.0127,  0.0011,  0.0568, -0.0591, -0.0120, -0.0725, -0.0658,  0.0821,
         -0.0629,  0.0038]], grad_fn=<AddmmBackward0>)

# LeakyReLU 4 hidden layer

In [17]:
### (2 - module) 4 hidden layer - LeakyReLU
class CustomModel_4H_2(Module):
    def __init__(self, in_fs, out_fs, n_cls):
        super().__init__()
        self.hidden1 = Linear(in_features=in_fs, out_features=out_fs)
        self.act1 = LeakyReLU()

        self.hidden2 = Linear(in_features=out_fs, out_features=out_fs)
        self.act2 = LeakyReLU()

        self.hidden3 = Linear(in_features=out_fs, out_features=out_fs)
        self.act3 = LeakyReLU()

        self.hidden4 = Linear(in_features=out_fs, out_features=out_fs)
        self.act4 = LeakyReLU()
        self.classifier = Linear(in_features=out_fs, out_features=n_cls)

    def forward(self, inp):
        bs = inp.shape[0]
        inp = inp.view(bs, -1)

        out = self.hidden1(inp)
        out = self.act1(out)
        out = self.hidden2(out)
        out = self.act2(out)
        out = self.hidden3(out)
        out = self.act3(out)
        out = self.hidden4(out)
        out = self.act4(out)
        out = self.classifier(out)
        return out

inp = torch.rand(1,1,28,28)
out_fs = 200
m = CustomModel_4H_2(in_fs = (inp.shape[1] * inp.shape[2] * inp.shape[3]), out_fs = out_fs, n_cls = 10)
m(inp)

tensor([[-0.0286,  0.0014,  0.0078,  0.0460,  0.0589,  0.0038,  0.0688,  0.0082,
          0.0149, -0.0645]], grad_fn=<AddmmBackward0>)

# ELU 4 hidden layer 

In [18]:
### (3 - module) 4 hidden layer - ELU
class CustomModel_4H_3(Module):
    def __init__(self, in_fs, out_fs, n_cls):
        super().__init__()
        self.hidden1 = Linear(in_features=in_fs, out_features=out_fs)
        self.act1 = ELU()

        self.hidden2 = Linear(in_features=out_fs, out_features=out_fs)
        self.act2 = ELU()

        self.hidden3 = Linear(in_features=out_fs, out_features=out_fs)
        self.act3 = ELU()

        self.hidden4 = Linear(in_features=out_fs, out_features=out_fs)
        self.act4 = ELU()
        self.classifier = Linear(in_features=out_fs, out_features=n_cls)

    def forward(self, inp):
        bs = inp.shape[0]
        inp = inp.view(bs, -1)

        out = self.hidden1(inp)
        out = self.act1(out)
        out = self.hidden2(out)
        out = self.act2(out)
        out = self.hidden3(out)
        out = self.act3(out)
        out = self.hidden4(out)
        out = self.act4(out)
        out = self.classifier(out)
        return out

inp = torch.rand(1,1,28,28)
out_fs = 200
m = CustomModel_4H_3(in_fs = (inp.shape[1] * inp.shape[2] * inp.shape[3]), out_fs = out_fs, n_cls = 10)
m(inp)

tensor([[-0.0084, -0.0928,  0.0240,  0.1283, -0.0259,  0.0385, -0.0248,  0.0856,
         -0.0246, -0.0508]], grad_fn=<AddmmBackward0>)

In [ ]:
### (5 - module) 4 hidden layer - GELU
class CustomModel_4H_5(Module):
    def __init__(self, in_fs, out_fs, n_cls):
        super().__init__()
        self.hidden1 = Linear(in_features=in_fs, out_features=out_fs)
        self.act1 = PReLU()

        self.hidden2 = Linear(in_features=out_fs, out_features=out_fs)
        self.act2 = PReLU()

        self.hidden3 = Linear(in_features=out_fs, out_features=out_fs)
        self.act3 = PReLU()

        self.hidden4 = Linear(in_features=out_fs, out_features=out_fs)
        self.act4 = PReLU()
        self.classifier = Linear(in_features=out_fs, out_features=n_cls)

    def forward(self, inp):
        bs = inp.shape[0]
        inp = inp.view(bs, -1)

        out = self.hidden1(inp)
        out = self.act1(out)
        out = self.hidden2(out)
        out = self.act2(out)
        out = self.hidden3(out)
        out = self.act3(out)
        out = self.hidden4(out)
        out = self.act4(out)
        out = self.classifier(out)
        return out

inp = torch.rand(1,1,28,28)
out_fs = 200
m = CustomModel_4H_5(in_fs = (inp.shape[1] * inp.shape[2] * inp.shape[3]), out_fs = out_fs, n_cls = 10)
m(inp)

tensor([[ 0.0364,  0.0153, -0.0659,  0.0599, -0.0161,  0.0271, -0.0504,  0.0973,
          0.0437,  0.0198]], grad_fn=<AddmmBackward0>)

In [21]:
### (6 - module) 4 hidden layer - SiLU
class CustomModel_4H_6(Module):
    def __init__(self, in_fs, out_fs, n_cls):
        super().__init__()
        self.hidden1 = Linear(in_features=in_fs, out_features=out_fs)
        self.act1 = SiLU()

        self.hidden2 = Linear(in_features=out_fs, out_features=out_fs)
        self.act2 = SiLU()

        self.hidden3 = Linear(in_features=out_fs, out_features=out_fs)
        self.act3 = SiLU()

        self.hidden4 = Linear(in_features=out_fs, out_features=out_fs)
        self.act4 = SiLU()
        self.classifier = Linear(in_features=out_fs, out_features=n_cls)

    def forward(self, inp):
        bs = inp.shape[0]
        inp = inp.view(bs, -1)

        out = self.hidden1(inp)
        out = self.act1(out)
        out = self.hidden2(out)
        out = self.act2(out)
        out = self.hidden3(out)
        out = self.act3(out)
        out = self.hidden4(out)
        out = self.act4(out)
        out = self.classifier(out)
        return out

inp = torch.rand(1,1,28,28)
out_fs = 200
m = CustomModel_4H_6(in_fs = (inp.shape[1] * inp.shape[2] * inp.shape[3]), out_fs = out_fs, n_cls = 10)
m(inp)

tensor([[-0.0067, -0.0545,  0.0598,  0.0466,  0.0016, -0.0269,  0.0627,  0.0485,
          0.0308, -0.0371]], grad_fn=<AddmmBackward0>)

 # Output Layerda asosan:
 # Sigmoid;
 # SoftMax; activationlar ishlatiladi.

In [25]:
### 4 hidden layer - ReLu out with Softmax
class CustomModel_4H_Soft(Module):
    def __init__(self, in_fs, out_fs, n_cls):
        super().__init__()
        self.hidden1 = Linear(in_features=in_fs, out_features=out_fs)
        self.act1 = ReLU()

        self.hidden2 = Linear(in_features=out_fs, out_features=out_fs)
        self.act2 = ReLU()

        self.hidden3 = Linear(in_features=out_fs, out_features=out_fs)
        self.act3 = ReLU()

        self.hidden4 = Linear(in_features=out_fs, out_features=out_fs)
        self.act4 = ReLU()

        self.classifier = Linear(in_features=out_fs, out_features=n_cls)
        self.act5 = Softmax(dim=1)

    def forward(self, inp):
        bs = inp.shape[0]
        inp = inp.view(bs, -1)

        out = self.hidden1(inp)
        out = self.act1(out)
        out = self.hidden2(out)
        out = self.act2(out)
        out = self.hidden3(out)
        out = self.act3(out)
        out = self.hidden4(out)
        out = self.act4(out)
        out = self.classifier(out)
        out = self.act5(out)
        return out

inp = torch.rand(1,1,28,28)
out_fs = 200
m = CustomModel_4H_Soft(in_fs = (inp.shape[1] * inp.shape[2] * inp.shape[3]), out_fs = out_fs, n_cls = 10)
pred = m(inp)
pred

tensor([[0.0976, 0.1001, 0.0974, 0.0975, 0.1032, 0.0993, 0.1001, 0.1061, 0.1002,
         0.0985]], grad_fn=<SoftmaxBackward0>)

In [26]:
pred.sum(dim=1) 

tensor([1.0000], grad_fn=<SumBackward1>)

In [29]:
### 4 hidden layer - ReLu out with Sigmoid
class CustomModel_4H_Sig(Module):
    def __init__(self, in_fs, out_fs, n_cls):
        super().__init__()
        self.hidden1 = Linear(in_features=in_fs, out_features=out_fs)
        self.act1 = ReLU()

        self.hidden2 = Linear(in_features=out_fs, out_features=out_fs)
        self.act2 = ReLU()

        self.hidden3 = Linear(in_features=out_fs, out_features=out_fs)
        self.act3 = ReLU()

        self.hidden4 = Linear(in_features=out_fs, out_features=out_fs)
        self.act4 = ReLU()
        self.classifier = Linear(in_features=out_fs, out_features=n_cls)
        self.act5 = Sigmoid()

    def forward(self, inp):
        bs = inp.shape[0]
        inp = inp.view(bs, -1)

        out = self.hidden1(inp)
        out = self.act1(out)
        out = self.hidden2(out)
        out = self.act2(out)
        out = self.hidden3(out)
        out = self.act3(out)
        out = self.hidden4(out)
        out = self.act4(out)
        out = self.classifier(out)
        out = self.act5(out)
        return out

inp = torch.rand(1,1,28,28)
out_fs = 200
m = CustomModel_4H_Sig(in_fs = (inp.shape[1] * inp.shape[2] * inp.shape[3]), out_fs = out_fs, n_cls = 1)
m(inp)

tensor([[0.5086]], grad_fn=<SigmoidBackward0>)